# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 650)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.inputText = QtWidgets.QTextEdit(self.splitter)
        self.inputText.setObjectName("inputText")
        self.outputText = QtWidgets.QTextEdit(self.splitter)
        self.outputText.setReadOnly(True)
        self.outputText.setCursorWidth(0)
        self.outputText.setObjectName("outputText")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.addToolBarBreak()
        self.formatBar = self.addToolBar("Format")

        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon3)
        self.actionPrint.setObjectName("actionPrint")

        self.actionPrintPreview = QtWidgets.QAction(MainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("icons/preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrintPreview.setIcon(icon33)
        self.actionPrintPreview.setObjectName("actionPreview")

        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap("icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon44)
        self.actionUndo.setObjectName("actionUndo")

        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon55 = QtGui.QIcon()
        icon55.addPixmap(QtGui.QPixmap("icons/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon55)
        self.actionRedo.setObjectName("actionRedo")

        self.actionInsertBlockquotes = QtWidgets.QAction(MainWindow)
        icon66 = QtGui.QIcon()
        icon66.addPixmap(QtGui.QPixmap("icons/blockquotes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertBlockquotes.setIcon(icon66)
        self.actionInsertBlockquotes.setObjectName("actionInsertBlockquotes")

        self.actionBold = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon4)
        self.actionBold.setObjectName("actionBold")
        self.actionInsertline = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertline.setIcon(icon5)
        self.actionInsertline.setObjectName("actionInsertline")
        self.actionItalic = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalic.setIcon(icon6)
        self.actionItalic.setObjectName("actionItalic")
        self.actionH1 = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/titleH1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionH1.setIcon(icon7)
        self.actionH1.setObjectName("actionH1")
        self.actionH2 = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/titleH2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionH2.setIcon(icon8)
        self.actionH2.setObjectName("actionH2")
        self.actionH3 = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/titleH3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionH3.setIcon(icon9)
        self.actionH3.setObjectName("actionH3")
        self.actionIndent = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/indentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIndent.setIcon(icon10)
        self.actionIndent.setObjectName("actionIndent")
        self.actionInsertLink = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertLink.setIcon(icon11)
        self.actionInsertLink.setObjectName("actionInsertLink")
        self.actionList = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionList.setIcon(icon12)
        self.actionList.setObjectName("actionList")
        self.actionNumbererList = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/numberedlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNumbererList.setIcon(icon13)
        self.actionNumbererList.setObjectName("actionNumbererList")
        self.actionInsertImage = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertImage.setIcon(icon14)
        self.actionInsertImage.setObjectName("actionInsertImage")
        self.actionExportPDF = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/pdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportPDF.setIcon(icon15)
        self.actionExportPDF.setObjectName("actionExportPDF")
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionPrintPreview)
        self.toolBar.addAction(self.actionExportPDF)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)

        self.formatBar.addAction(self.actionBold)
        self.formatBar.addAction(self.actionItalic)
        self.formatBar.addAction(self.actionH1)
        self.formatBar.addAction(self.actionH2)
        self.formatBar.addAction(self.actionH3)
        self.formatBar.addAction(self.actionList)
        self.formatBar.addAction(self.actionNumbererList)
        self.formatBar.addAction(self.actionIndent)
        self.formatBar.addSeparator()

        self.formatBar.addAction(self.actionInsertLink)
        self.formatBar.addAction(self.actionInsertline)
        self.formatBar.addAction(self.actionInsertImage)
        self.formatBar.addAction(self.actionInsertBlockquotes)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow", "New File"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open File"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "SaveFile"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint.setToolTip(_translate("MainWindow", "Print File"))
        self.actionPrintPreview.setText(_translate("MainWindow", "Print Preview"))
        self.actionPrintPreview.setToolTip(_translate("MainWindow", "Print Preview"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setToolTip(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setToolTip(_translate("MainWindow", "Redo"))
        self.actionInsertBlockquotes.setText(_translate("MainWindow", "Insert Blockquotes"))
        self.actionInsertBlockquotes.setToolTip(_translate("MainWindow", "Insert Blockquotes"))

        self.actionBold.setText(_translate("MainWindow", "Bold"))
        self.actionBold.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionInsertline.setText(_translate("MainWindow", "Horizontal Rule"))
        self.actionItalic.setText(_translate("MainWindow", "Italic"))
        self.actionH1.setText(_translate("MainWindow", "H1"))
        self.actionH2.setText(_translate("MainWindow", "H2"))
        self.actionH3.setText(_translate("MainWindow", "H3"))
        self.actionIndent.setText(_translate("MainWindow", "Indent Block Code"))
        self.actionInsertLink.setText(_translate("MainWindow", "Insert Link"))
        self.actionList.setText(_translate("MainWindow", "List"))
        self.actionNumbererList.setText(_translate("MainWindow", "Numberer List"))
        self.actionInsertImage.setText(_translate("MainWindow", "Insert Image"))
        self.actionExportPDF.setText(_translate("MainWindow", "Export PDF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

